import { calculateFourPillars } from 'https://cdn.jsdelivr.net/npm/manseryeok@2.0.0/+esm';
import { firebaseConfig } from './firebase-config.js?v=20260907-1645';
import { initializeApp, getApps, getApp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import { getFirestore, doc, getDoc } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';

const tool=document.body.dataset.quickTool;
const form=document.querySelector('[data-quick-form]');
if(!tool||!form) throw new Error('quick tool form missing');
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const status=form.querySelector('[data-quick-status]'),profileState=form.querySelector('[data-profile-state]');
const nameInput=form.querySelector('#quick-name'),birthDateInput=form.querySelector('#quick-birth-date'),birthTimeInput=form.querySelector('#quick-birth-time'),timeUnknown=form.querySelector('#quick-time-unknown'),calendar=form.querySelector('#quick-calendar'),gender=form.querySelector('#quick-gender');
const result=document.querySelector('[data-quick-result]'),resultBody=document.querySelector('[data-quick-result-body]'),resultTitle=document.querySelector('[data-quick-result-title]'),resultLead=document.querySelector('[data-quick-result-lead]');
const branchOrder=['자','축','인','묘','진','사','오','미','신','유','술','해'];
const branchToZodiac={자:'rat',축:'ox',인:'tiger',묘:'rabbit',진:'dragon',사:'snake',오:'horse',미:'goat',신:'monkey',유:'rooster',술:'dog',해:'pig'};
const yukhap=[['자','축'],['인','해'],['묘','술'],['진','유'],['사','신'],['오','미']];
const chung=[['자','오'],['축','미'],['인','신'],['묘','유'],['진','술'],['사','해']];
const hae=[['자','미'],['축','오'],['인','사'],['묘','진'],['신','해'],['유','술']];
const pa=[['자','유'],['축','진'],['인','해'],['묘','오'],['사','신'],['미','술']];
const samhap=[['신','자','진'],['해','묘','미'],['인','오','술'],['사','유','축']];
const hyeongGroups=[['인','사','신'],['축','미','술']];
const pairHas=(arr,a,b)=>arr.some(p=>p.includes(a)&&p.includes(b));
const isHyeong=(a,b)=>(a===b&&['진','오','유','해'].includes(a))||pairHas([['자','묘']],a,b)||hyeongGroups.some(g=>g.includes(a)&&g.includes(b));
const stemElement={갑:'wood',을:'wood',병:'fire',정:'fire',무:'earth',기:'earth',경:'metal',신:'metal',임:'water',계:'water'};
const elementKo={wood:'시작·성장',fire:'표현·활동',earth:'안정·관리',metal:'판단·정리',water:'관찰·유연'};
const purposeLabels={contract:'계약·서명',open:'개업·오픈',interview:'면접·중요 미팅',exam:'시험·평가',presentation:'발표·제안',project:'프로젝트 시작',relationship:'고백·관계 시작',travel:'여행·출발'};
const purposeElements={contract:{metal:10,earth:6},open:{wood:10,fire:8},interview:{fire:10,metal:6},exam:{water:8,metal:6},presentation:{fire:9,water:5},project:{wood:10,fire:6},relationship:{fire:8,wood:6},travel:{water:8,wood:5}};
const businessPurpose=new Set(['contract','open','interview','exam','presentation','project']);

const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pillarString=v=>typeof v==='string'?v:(v?.korean||v?.name||'');
const pad=n=>String(n).padStart(2,'0');
const dateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x;};
const fmtDate=s=>new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short'}).format(new Date(`${s}T12:00:00`));
function seoulToday(offset=0){const now=new Date(Date.now()+offset*86400000);const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);const get=t=>parts.find(p=>p.type===t)?.value||'';return `${get('year')}-${get('month')}-${get('day')}`;}
function calcPillars(dateString,{time='12:00',isLunar=false,genderValue=''}={}){const [year,month,day]=dateString.split('-').map(Number);const [hour,minute]=String(time||'12:00').split(':').map(Number);const r=calculateFourPillars({year,month,day,hour:Number.isFinite(hour)?hour:12,minute:Number.isFinite(minute)?minute:0,isLunar,gender:genderValue||undefined});return typeof r?.toObject==='function'?r.toObject():r;}
function dayParts(dateString,opts={}){const o=calcPillars(dateString,opts),p=pillarString(o?.day);return {pillar:p,stem:[...p][0],branch:[...p][1]};}
function yearZodiac(dateString,opts={}){const o=calcPillars(dateString,opts),p=pillarString(o?.year),b=[...p][1];return branchToZodiac[b]||branchToZodiac[branchOrder[(Number(dateString.slice(0,4))-4)%12]]||'rat';}
function relationScore(a,b){if(pairHas(yukhap,a,b))return {score:18,label:'서로 자연스럽게 맞물리는 흐름'};if(samhap.some(g=>g.includes(a)&&g.includes(b)))return {score:12,label:'연결이 부드러운 흐름'};if(pairHas(chung,a,b))return {score:-18,label:'속도와 방향이 부딪히기 쉬운 흐름'};if(isHyeong(a,b))return {score:-12,label:'긴장과 반복을 점검할 흐름'};if(pairHas(hae,a,b))return {score:-10,label:'말과 의도를 한 번 더 확인할 흐름'};if(pairHas(pa,a,b))return {score:-7,label:'작은 어긋남을 정리할 흐름'};if(a===b)return {score:5,label:'익숙한 성향이 강해지는 흐름'};return {score:0,label:'큰 충돌 없이 무난한 흐름'};}
function dateScore(birth,date,purpose=''){const b=dayParts(birth,{time:birthTimeInput?.value||'12:00',isLunar:calendar?.value==='lunar',genderValue:gender?.value||''}),d=dayParts(date),rel=relationScore(b.branch,d.branch);let score=55+rel.score;const el=stemElement[d.stem],bonus=purposeElements[purpose]?.[el]||0;score+=bonus;const weekday=new Date(`${date}T12:00:00`).getDay();if(businessPurpose.has(purpose)){score+=weekday>=1&&weekday<=5?4:-4;}return {date,score,rel,day:d,element:el};}
function reasonFor(item,purpose){const p=purposeLabels[purpose]||'중요한 일정';const purposeCopy=item.element?`${elementKo[item.element]} 성향이 ${p}의 목적과 비교적 잘 맞습니다.`:'';return `${item.rel.label}. ${purposeCopy}`.trim();}
function setDateDefaults(){const start=form.querySelector('#quick-start'),end=form.querySelector('#quick-end');if(start&&!start.value)start.value=seoulToday(tool==='moving'?7:1);if(end&&!end.value)end.value=seoulToday(tool==='moving'?60:30);if(tool==='tomorrow'){const label=document.querySelector('[data-target-date]');if(label)label.textContent=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date(`${seoulToday(1)}T12:00:00`));}}
setDateDefaults();

function syncTime(){if(!birthTimeInput||!timeUnknown)return;birthTimeInput.disabled=timeUnknown.checked;if(timeUnknown.checked)birthTimeInput.value='';}
timeUnknown?.addEventListener('change',syncTime);syncTime();

onAuthStateChanged(auth,async user=>{if(!profileState)return;if(!user){profileState.textContent='비회원은 기본 정보를 직접 입력해주세요.';return;}try{const snap=await getDoc(doc(db,'users',user.uid));if(!snap.exists()){profileState.textContent='저장된 회원정보가 없어 직접 입력해주세요.';return;}const p=snap.data();if(p.name&&nameInput)nameInput.value=p.name;if(p.birthDate&&birthDateInput)birthDateInput.value=p.birthDate;if(p.birthTime&&birthTimeInput&&!p.birthTimeUnknown)birthTimeInput.value=p.birthTime;if(timeUnknown)timeUnknown.checked=Boolean(p.birthTimeUnknown);if(calendar&&p.calendarType)calendar.value=p.calendarType;if(gender&&p.gender)gender.value=p.gender;syncTime();profileState.dataset.state='ok';profileState.textContent='저장된 회원정보를 불러왔습니다.';}catch(e){profileState.textContent='회원정보를 불러오지 못했습니다. 직접 입력해도 이용할 수 있습니다.';}});

function validate(){status.textContent='';if(!nameInput?.value.trim()){status.textContent='이름 또는 닉네임을 입력해주세요.';nameInput?.focus();return false;}if(!birthDateInput?.value){status.textContent='태어난 날짜를 입력해주세요.';birthDateInput?.focus();return false;}if(!form.elements.consent?.checked){status.textContent='분석을 위한 정보 사용에 동의해주세요.';return false;}return true;}
function birthBase(){return {name:nameInput.value.trim(),birthDate:birthDateInput.value,birthYear:Number(birthDateInput.value.slice(0,4)),birthWeekday:new Intl.DateTimeFormat('ko-KR',{weekday:'long'}).format(new Date(`${birthDateInput.value}T12:00:00`)),birthTime:birthTimeInput?.value||'',birthTimeUnknown:Boolean(timeUnknown?.checked),calendarType:calendar?.value||'solar',gender:gender?.value||''};}
function showResult(title,lead,html){resultTitle.textContent=title;resultLead.textContent=lead;resultBody.innerHTML=html;result.hidden=false;setTimeout(()=>result.scrollIntoView({behavior:'smooth',block:'start'}),50);}
function hashSeed(str){let h=2166136261;for(const ch of str){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function randomFromSeed(seed){let x=seed||1;return ()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return (x>>>0)/4294967296;};}
function rangeDates(start,end,max=90){const out=[],s=new Date(`${start}T12:00:00`),e=new Date(`${end}T12:00:00`);for(let d=new Date(s);d<=e&&out.length<max;d=addDays(d,1))out.push(dateKey(d));return out;}

function runTomorrow(){const b=birthBase(),targetDate=seoulToday(1),zodiac=yearZodiac(b.birthDate,{isLunar:b.calendarType==='lunar',genderValue:b.gender});sessionStorage.setItem('jungwoljae_fortune_input',JSON.stringify({...b,zodiac,targetDate,mode:'tomorrow',createdAt:Date.now()}));location.href='./fortune-result.html';}
function runLucky(){const b=birthBase(),day=dayParts(seoulToday()),birth=dayParts(b.birthDate,{time:b.birthTime||'12:00',isLunar:b.calendarType==='lunar',genderValue:b.gender});const seed=hashSeed(`${b.birthDate}|${b.birthTime}|${day.pillar}|${birth.pillar}|${seoulToday()}`),rnd=randomFromSeed(seed),nums=[];while(nums.length<6){const n=1+Math.floor(rnd()*45);if(!nums.includes(n))nums.push(n);}nums.sort((a,c)=>a-c);const key=nums[Math.floor(rnd()*nums.length)];showResult(`${b.name}님의 오늘 참고 숫자`,`숫자 자체가 미래를 바꾸는 것은 아니지만, 오늘의 사주 흐름을 가볍게 숫자로 풀어본 결과입니다.`, `<div class="number-set">${nums.map(n=>`<span class="number-ball${n===key?' is-key':''}">${n}</span>`).join('')}</div><div class="quick-card-grid"><article class="quick-card"><small>중심 숫자</small><strong>${key}</strong><p>여섯 숫자 가운데 오늘 가장 중심에 둔 숫자입니다. 좌석·순서·예약번호처럼 선택지가 여러 개일 때 재미로 참고해보세요.</p></article><article class="quick-card"><small>숫자를 쓰는 법</small><strong>정답보다 작은 선택에 가볍게</strong><p>복권·투자 결과를 보장하는 숫자가 아닙니다. 숫자 운세는 오늘의 기분 전환과 선택 기준을 가볍게 만드는 콘텐츠로 활용해주세요.</p></article></div><div class="quick-note"><strong>계산 기준</strong> · 출생일의 사주 구조와 오늘의 일진을 고정된 방식으로 조합해 같은 날짜·같은 입력에는 같은 숫자가 나오도록 구성했습니다.</div>`);}
function runImportant(){const start=form.querySelector('#quick-start').value,end=form.querySelector('#quick-end').value,purpose=form.querySelector('#quick-purpose').value;if(!start||!end||!purpose){status.textContent='용도와 날짜 범위를 모두 선택해주세요.';return;}if(new Date(start)>new Date(end)){status.textContent='시작일이 종료일보다 늦습니다.';return;}const b=birthBase(),items=rangeDates(start,end,62).map(d=>dateScore(b.birthDate,d,purpose)).sort((a,c)=>c.score-a.score).slice(0,5);showResult(`${purposeLabels[purpose]}에 참고할 날짜`,`사주와 날짜의 관계를 간단히 비교해, 선택한 기간 안에서 상대적으로 무리가 적은 날짜를 먼저 보여드립니다.`, `<div class="date-ranking">${items.map((it,i)=>`<article class="date-row"><span class="rank">${i+1}</span><div><time>${fmtDate(it.date)}</time><p>${esc(reasonFor(it,purpose))}</p></div><span class="score">추천 ${Math.max(1,Math.min(99,Math.round(it.score)))}</span></article>`).join('')}</div><div class="quick-note"><strong>간편 택일 안내</strong> · 중요한 계약·개업·시험처럼 실제 결과가 큰 일정은 업무 조건, 기관 운영일, 당사자 사정이 우선입니다. 정월재의 날짜 추천은 출생일과 해당 날짜의 명리 관계를 비교한 참고용 순위입니다.</div>`);}
function runMoving(){const start=form.querySelector('#quick-start').value,end=form.querySelector('#quick-end').value,type=form.querySelector('#quick-move-type').value;if(!start||!end){status.textContent='이사 예정 기간을 선택해주세요.';return;}if(new Date(start)>new Date(end)){status.textContent='시작일이 종료일보다 늦습니다.';return;}const b=birthBase(),items=rangeDates(start,end,90).map(d=>{const it=dateScore(b.birthDate,d,'');if(it.element==='earth')it.score+=10;if(it.element==='wood')it.score+=5;const wd=new Date(`${d}T12:00:00`).getDay();if(form.querySelector('#quick-weekend')?.checked&&[0,6].includes(wd))it.score+=5;return it;}).sort((a,c)=>c.score-a.score),best=items.slice(0,5),avoid=[...items].sort((a,c)=>a.score-c.score).slice(0,3);const typeLabel={home:'주거 이사',office:'사무실 이전',movein:'입주'}[type]||'이사';showResult(`${b.name}님의 ${typeLabel} 후보일`,`정착과 이동의 리듬을 함께 보고, 선택한 기간에서 상대적으로 편안한 날짜를 추렸습니다.`, `<div class="date-ranking">${best.map((it,i)=>`<article class="date-row"><span class="rank">${i+1}</span><div><time>${fmtDate(it.date)}</time><p>${esc(it.rel.label)}. 정리·정착의 흐름을 함께 고려한 후보일입니다.</p></div><span class="score">추천 ${Math.max(1,Math.min(99,Math.round(it.score)))}</span></article>`).join('')}</div><div class="quick-card-grid" style="margin-top:14px"><article class="quick-card"><small>피하면 좋은 후보</small><strong>${avoid.map(x=>fmtDate(x.date)).join(' · ')}</strong><p>선택한 기간 안에서 상대적으로 충돌이나 긴장이 크게 잡힌 날짜입니다. 실제 계약·입주 일정이 정해져 있다면 무리해서 바꿀 필요는 없습니다.</p></article><article class="quick-card"><small>현실적으로 먼저 볼 것</small><strong>계약·엘리베이터·입주 가능시간이 우선</strong><p>택일은 실제 이사 조건을 대신하지 않습니다. 관리사무소, 이사업체, 잔금·등기 일정이 가능한 날짜 중에서 후보를 좁히는 방식으로 활용해주세요.</p></article></div><div class="quick-note"><strong>간편 이사 택일</strong> · 출생일과 후보 날짜의 합·충·형·해 관계, 정착과 관련된 날짜 성향을 간단히 조합한 참고 기능입니다.</div>`);}

form.addEventListener('submit',e=>{e.preventDefault();if(!validate())return;try{if(tool==='tomorrow')runTomorrow();else if(tool==='lucky-number')runLucky();else if(tool==='important-day')runImportant();else if(tool==='moving')runMoving();}catch(err){console.error(err);status.textContent='계산 중 오류가 발생했습니다. 입력 정보를 다시 확인해주세요.';}});
